# Generated by Django 2.1.5 on 2019-03-12 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crystaluse', models.CharField(choices=[('M', 'Mental'), ('P', 'Physical'), ('S', 'Spiritual')], default='M', max_length=1)),
                ('crystal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Crystal')),
            ],
        ),
    ]
