# Generated by Django 2.1.5 on 2019-03-12 21:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_uses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uses',
            old_name='crystaluse',
            new_name='used',
        ),
        migrations.AddField(
            model_name='uses',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date used'),
        ),
    ]
