# Generated by Django 2.1.5 on 2019-03-13 18:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190312_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Country Name')),
            ],
        ),
        migrations.AlterModelOptions(
            name='uses',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='crystal',
            name='healingproperties',
            field=models.TextField(verbose_name='Healing Properties'),
        ),
        migrations.AlterField(
            model_name='uses',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date Used'),
        ),
        migrations.AddField(
            model_name='crystal',
            name='countries',
            field=models.ManyToManyField(to='main_app.Country'),
        ),
    ]
